spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:change-me-please-change-me-please-change-me-please-64}
  issuer: school-api
  access-token-minutes: 60

management:
  endpoints:
    web:
      exposure:
        include:
            - health
            - info
            - metrics
            - prometheus
  endpoint.health.probes.enabled: true
