spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include:
            - health
            - info
            - metrics
            - prometheus
  endpoint.health.probes.enabled: true
